Bug #50648: settings/syntax: fix decoding of oldattr
python3 /usr/lib/python3/dist-packages/univention/admincli/admin.py settings/syntax list
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 1129, in <module>
    print('\n'.join(doit(sys.argv)))
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 411, in doit
    out = _doit(arglist)
  File "/usr/lib/python3/dist-packages/univention/admincli/admin.py", line 987, in _doit
    object.open()
  File "/usr/lib/python3/dist-packages/univention/admin/handlers/settings/syntax.py", line 166, in open
    if ':' in item:
TypeError: a bytes-like object is required, not 'str'